### ISSUE TITLE
Pyproject migration & package publishing

### ISSUE THREAD

**Issue by georgkrause** [metabrainz/listenbrainz-content-resolver#39]
In order to align this project to other MB projects I want to migrate the package metadata to `pyproject.toml` and automate the build and publishing of the package.

Some pre-condition need to be met before:

- [ ] Tag a release of lb-matching-tools
- [x] Get rid of git dependencies

**Comment by georgkrause** [comment]
@phw Do you see any potential issues when it comes to the PyInstaller? Do we need special build scripts?

**Comment by phw** [comment]
@georgkrause No, I don't think so. Running `pyinstaller` on the project will require installed dependencies. So that part is independent and needs to be run on its own.

Only thing we can consider is including some documentation for building.

**Comment by mayhem** [comment]
py-sonic git depedency is now cleaned up.

**Comment by georgkrause** [comment]
@mayhem Can you assign me this?

**Comment by ShashankSrivastava2002** [comment]
@georgkrause  can you assign me this??

**Comment by mayhem** [comment]
This project is in the process of being merged into the Troi project. No further work should be done on it.
